version: "3.3"
services:
  app:
    build: .
    environment:
      API_URL: ""
      RUNNER_BASE_IMAGE: "alpine:latest"
      RUNNER_ENV: "QWEWQEW=ASDDSA"
      DEBUG: "true"
      DOCKER_API_URL: ""
      DOCKER_PULL_POLICY: ""
